FROM node:21.6.1-alpine3.19

WORKDIR /usr/src/app

COPY ../../../../package.json ./
COPY ../../../../package-lock.json ./

RUN npm install
COPY ../../../../tsconfig.json ./
COPY ../../../../src/acceptance/ ./src/acceptance

CMD ["npm", "run", "acceptance"]
