FROM node:alpine

WORKDIR /usr/src/app

COPY ../../../../package.json package-lock.json ./

RUN npm install
COPY tsconfig.json ./
COPY src/acceptance/ ./src/acceptance
RUN npm run acceptance

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:4444/wd/hub || exit 1