FROM node:alpine as build-deps

WORKDIR /usr/src/app

COPY ../../../../package.json package-lock.json ./

RUN npm install
COPY .mocharc.json ./
COPY tsconfig.json ./
COPY webpack.config.js ./
COPY src/main/ ./src/main
COPY src/test/ ./src/test
RUN npm test
RUN npm run build:prod

FROM nginx:1.12-alpine
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]